name: ci

on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

jobs:
    ci:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [18]

        steps:
            - name: Checkout 🛎
              uses: actions/checkout@master

            - name: Setup node env 🏗
              uses: actions/setup-node@v3.4.1
              with:
                  node-version: ${{ matrix.node }}
                  check-latest: true

            - name: Cache node_modules 📦
              uses: actions/cache@v3.3.1
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install dependencies 👨🏻‍💻
              run: npm ci --prefer-offline --no-audit

            - name: Run linter 👀
              run: npm run lint

            - name: Run tests 🧪
              env:
                  GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
                  GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
                  GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
                  SENDGRID_API_TOKEN: ${{ secrets.SENDGRID_API_TOKEN }}
                  ATLASSIAN_APP_PASSWORD: ${{ secrets.ATLASSIAN_APP_PASSWORD }}
                  ATLASSIAN_USERNAME: ${{ env.ATLASSIAN_USERNAME }}
                  GH_USERNAME: ${{ env.GH_USERNAME }}
                  GOOGLE_CALENDAR_ID: ${{ env.GOOGLE_CALENDAR_ID }}
              run: npm run test
